Repository GetStream/stream-feeds-swift, pull requests merged in 2025-09, with the labels that each got.

#15 Add StateLayerEventPublisher for centralised change handling
  Sources/StreamFeeds/Extensions/Array+Extensions.swift
  Sources/StreamFeeds/FeedsClient.swift
  Sources/StreamFeeds/Models/ActivityData.swift
  Sources/StreamFeeds/Models/FeedsReactionData.swift
  Sources/StreamFeeds/Repositories/ActivitiesRepository.swift
  Sources/StreamFeeds/StateLayer/Activity.swift
  Sources/StreamFeeds/StateLayer/ActivityState+Observer.swift
  Sources/StreamFeeds/StateLayer/ActivityState.swift
  Sources/StreamFeeds/StateLayer/Common/StateLayerEvent.swift
  Sources/StreamFeeds/StateLayer/Common/StateLayerEventPublisher.swift
  Sources/StreamFeeds/StateLayer/Feed.swift
  Tests/StreamFeedsTests/StateLayer/ActivityCommentList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/Activity_Tests.swift
  Tests/StreamFeedsTests/StateLayer/Feed_Tests.swift
  Tests/StreamFeedsTests/TestTools/APITransportMock.swift
  Tests/StreamFeedsTests/TestTools/ActivityAddedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/ActivityResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/ActivityUpdatedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/AddReactionResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/CommentAddedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/CommentDeletedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/CommentReactionAddedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/CommentReactionDeletedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/CommentResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/CommentUpdatedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/DeleteActivityReactionResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/FeedsReactionResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/GetActivityResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/GetCommentsResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PinActivityResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollClosedFeedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollDeletedFeedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollOptionResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollOptionResponseData+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollResponseData+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollUpdatedFeedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteCastedFeedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteChangedFeedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteRemovedFeedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteResponseData+Testing.swift
  Tests/StreamFeedsTests/TestTools/ReactionGroupResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/Response+Testing.swift
  Tests/StreamFeedsTests/TestTools/ThreadedCommentResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/UnpinActivityResponse+Testing.swift
Labels: ✅ Feature

#17 [CI] Get rid of mint package manager
  .github/actions/bootstrap/action.yml
  .github/workflows/sonar.yml
  AGENTS.md
  Githubfile
  Mintfile
  Scripts/bootstrap.sh
  Scripts/generate.sh
  fastlane/Fastfile
  lefthook.yml
Labels: CI/CD

#19 Update state for Activity.ownBookmarks in Activity and Feed
  Sources/StreamFeeds/StateLayer/ActivityState.swift
  Sources/StreamFeeds/StateLayer/FeedState.swift
Labels: 🐞 Bug

#28 Add FeedList unit tests
  .gitignore
  Tests/StreamFeedsTests/StateLayer/ActivityReactionList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/FeedList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/Feed_Tests.swift
  Tests/StreamFeedsTests/TestTools/APITransportMock.swift
  Tests/StreamFeedsTests/TestTools/FeedMemberResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/FeedResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/FeedUpdatedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/FeedsReactionResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PinActivityResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollResponseData+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteResponseData+Testing.swift
  Tests/StreamFeedsTests/TestTools/QueryFeedsResponse+Testing.swift
Labels: CI/CD

#29 Add MemberList unit tests
  Tests/StreamFeedsTests/StateLayer/MemberList_Tests.swift
  Tests/StreamFeedsTests/TestTools/FeedMemberRemovedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/FeedMemberUpdatedEvent+Testing.swift
Labels: CI/CD

#30 Use StateLayerEventPublisher in remaining paginated lists
  Sources/StreamFeeds/Extensions/Array+Extensions.swift
  Sources/StreamFeeds/Models/FollowData.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/ActivityCommentList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/ActivityList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/ActivityListState.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/ActivityReactionList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentReactionList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentReactionListState+Observer.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentReactionListState.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentReplyList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentReplyListState+Observer.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/CommentReplyListState.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/FollowList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/FollowListState+Observer.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/FollowListState.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/ModerationConfigList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/ModerationConfigListState.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/PollList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/PollListState+Observer.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/PollListState.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/PollVoteList.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/PollVoteListState+Observer.swift
  Sources/StreamFeeds/StateLayer/PaginatedLists/PollVoteListState.swift
  Tests/StreamFeedsTests/StateLayer/CommentReactionList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/CommentReplyList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/FollowList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/ModerationConfigList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/PollList_Tests.swift
  Tests/StreamFeedsTests/StateLayer/PollVoteList_Tests.swift
  Tests/StreamFeedsTests/TestTools/ConfigResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/FeedMemberResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/GetCommentRepliesResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/MemberRemovedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/MemberUpdatedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollDeletedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollUpdatedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteCastedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteChangedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVoteDeletedEvent+Testing.swift
  Tests/StreamFeedsTests/TestTools/PollVotesResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/QueryCommentReactionsResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/QueryFollowsResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/QueryModerationConfigsResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/QueryPollsResponse+Testing.swift
  Tests/StreamFeedsTests/TestTools/ThreadedCommentResponse+Testing.swift
Labels: ✅ Feature

#36 Add FeedsClient unit tests
  Githubfile
  Tests/StreamFeedsTests/FeedsClient_Test.swift
Labels: CI/CD
